//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.RepCajaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepCaja", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class RepCaja : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string banco_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cliente_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cliente_rifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cotizacion_valorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuenta_numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instrumento_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_controlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operacion_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string banco_nombre {
            get {
                return this.banco_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.banco_nombreField, value) != true)) {
                    this.banco_nombreField = value;
                    this.RaisePropertyChanged("banco_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cliente_nombre {
            get {
                return this.cliente_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.cliente_nombreField, value) != true)) {
                    this.cliente_nombreField = value;
                    this.RaisePropertyChanged("cliente_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cliente_rif {
            get {
                return this.cliente_rifField;
            }
            set {
                if ((object.ReferenceEquals(this.cliente_rifField, value) != true)) {
                    this.cliente_rifField = value;
                    this.RaisePropertyChanged("cliente_rif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cotizacion_valor {
            get {
                return this.cotizacion_valorField;
            }
            set {
                if ((this.cotizacion_valorField.Equals(value) != true)) {
                    this.cotizacion_valorField = value;
                    this.RaisePropertyChanged("cotizacion_valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuenta_numero {
            get {
                return this.cuenta_numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.cuenta_numeroField, value) != true)) {
                    this.cuenta_numeroField = value;
                    this.RaisePropertyChanged("cuenta_numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instrumento_nombre {
            get {
                return this.instrumento_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.instrumento_nombreField, value) != true)) {
                    this.instrumento_nombreField = value;
                    this.RaisePropertyChanged("instrumento_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_control {
            get {
                return this.nro_controlField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_controlField, value) != true)) {
                    this.nro_controlField = value;
                    this.RaisePropertyChanged("nro_control");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_operacion {
            get {
                return this.nro_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_operacionField, value) != true)) {
                    this.nro_operacionField = value;
                    this.RaisePropertyChanged("nro_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operacion_nombre {
            get {
                return this.operacion_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.operacion_nombreField, value) != true)) {
                    this.operacion_nombreField = value;
                    this.RaisePropertyChanged("operacion_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RepCajaService.IRepCaja")]
    public interface IRepCaja {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCaja/GetCuentasDetalle", ReplyAction="http://tempuri.org/IRepCaja/GetCuentasDetalleResponse")]
        System.Collections.Generic.List<App.RepCajaService.RepCaja> GetCuentasDetalle(string idEmpresa, string id_moneda, string id_cuenta, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCaja/GetCuentasDetalle", ReplyAction="http://tempuri.org/IRepCaja/GetCuentasDetalleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCajaService.RepCaja>> GetCuentasDetalleAsync(string idEmpresa, string id_moneda, string id_cuenta, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCaja/GetCuentasResumen", ReplyAction="http://tempuri.org/IRepCaja/GetCuentasResumenResponse")]
        System.Collections.Generic.List<App.RepCajaService.RepCaja> GetCuentasResumen(string idEmpresa, string id_moneda, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCaja/GetCuentasResumen", ReplyAction="http://tempuri.org/IRepCaja/GetCuentasResumenResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCajaService.RepCaja>> GetCuentasResumenAsync(string idEmpresa, string id_moneda, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCaja/GetInstrumentosDetalle", ReplyAction="http://tempuri.org/IRepCaja/GetInstrumentosDetalleResponse")]
        System.Collections.Generic.List<App.RepCajaService.RepCaja> GetInstrumentosDetalle(string idEmpresa, string id_moneda, string id_instrumento, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCaja/GetInstrumentosDetalle", ReplyAction="http://tempuri.org/IRepCaja/GetInstrumentosDetalleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCajaService.RepCaja>> GetInstrumentosDetalleAsync(string idEmpresa, string id_moneda, string id_instrumento, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCaja/GetInstrumentosResumen", ReplyAction="http://tempuri.org/IRepCaja/GetInstrumentosResumenResponse")]
        System.Collections.Generic.List<App.RepCajaService.RepCaja> GetInstrumentosResumen(string idEmpresa, string id_moneda, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCaja/GetInstrumentosResumen", ReplyAction="http://tempuri.org/IRepCaja/GetInstrumentosResumenResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCajaService.RepCaja>> GetInstrumentosResumenAsync(string idEmpresa, string id_moneda, string desde, string hasta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepCajaChannel : App.RepCajaService.IRepCaja, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepCajaClient : System.ServiceModel.ClientBase<App.RepCajaService.IRepCaja>, App.RepCajaService.IRepCaja {
        
        public RepCajaClient() {
        }
        
        public RepCajaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepCajaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepCajaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepCajaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<App.RepCajaService.RepCaja> GetCuentasDetalle(string idEmpresa, string id_moneda, string id_cuenta, string desde, string hasta) {
            return base.Channel.GetCuentasDetalle(idEmpresa, id_moneda, id_cuenta, desde, hasta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCajaService.RepCaja>> GetCuentasDetalleAsync(string idEmpresa, string id_moneda, string id_cuenta, string desde, string hasta) {
            return base.Channel.GetCuentasDetalleAsync(idEmpresa, id_moneda, id_cuenta, desde, hasta);
        }
        
        public System.Collections.Generic.List<App.RepCajaService.RepCaja> GetCuentasResumen(string idEmpresa, string id_moneda, string desde, string hasta) {
            return base.Channel.GetCuentasResumen(idEmpresa, id_moneda, desde, hasta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCajaService.RepCaja>> GetCuentasResumenAsync(string idEmpresa, string id_moneda, string desde, string hasta) {
            return base.Channel.GetCuentasResumenAsync(idEmpresa, id_moneda, desde, hasta);
        }
        
        public System.Collections.Generic.List<App.RepCajaService.RepCaja> GetInstrumentosDetalle(string idEmpresa, string id_moneda, string id_instrumento, string desde, string hasta) {
            return base.Channel.GetInstrumentosDetalle(idEmpresa, id_moneda, id_instrumento, desde, hasta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCajaService.RepCaja>> GetInstrumentosDetalleAsync(string idEmpresa, string id_moneda, string id_instrumento, string desde, string hasta) {
            return base.Channel.GetInstrumentosDetalleAsync(idEmpresa, id_moneda, id_instrumento, desde, hasta);
        }
        
        public System.Collections.Generic.List<App.RepCajaService.RepCaja> GetInstrumentosResumen(string idEmpresa, string id_moneda, string desde, string hasta) {
            return base.Channel.GetInstrumentosResumen(idEmpresa, id_moneda, desde, hasta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCajaService.RepCaja>> GetInstrumentosResumenAsync(string idEmpresa, string id_moneda, string desde, string hasta) {
            return base.Channel.GetInstrumentosResumenAsync(idEmpresa, id_moneda, desde, hasta);
        }
    }
}
