//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.RepCompraService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepCompra", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class RepCompra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cotizacion_valorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_controlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_control_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proveedor_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proveedor_rifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_documento_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cotizacion_valor {
            get {
                return this.cotizacion_valorField;
            }
            set {
                if ((this.cotizacion_valorField.Equals(value) != true)) {
                    this.cotizacion_valorField = value;
                    this.RaisePropertyChanged("cotizacion_valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_documento {
            get {
                return this.fecha_documentoField;
            }
            set {
                if ((this.fecha_documentoField.Equals(value) != true)) {
                    this.fecha_documentoField = value;
                    this.RaisePropertyChanged("fecha_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_control {
            get {
                return this.nro_controlField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_controlField, value) != true)) {
                    this.nro_controlField = value;
                    this.RaisePropertyChanged("nro_control");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_control_documento {
            get {
                return this.nro_control_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_control_documentoField, value) != true)) {
                    this.nro_control_documentoField = value;
                    this.RaisePropertyChanged("nro_control_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_documento {
            get {
                return this.nro_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_documentoField, value) != true)) {
                    this.nro_documentoField = value;
                    this.RaisePropertyChanged("nro_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string proveedor_nombre {
            get {
                return this.proveedor_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.proveedor_nombreField, value) != true)) {
                    this.proveedor_nombreField = value;
                    this.RaisePropertyChanged("proveedor_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string proveedor_rif {
            get {
                return this.proveedor_rifField;
            }
            set {
                if ((object.ReferenceEquals(this.proveedor_rifField, value) != true)) {
                    this.proveedor_rifField = value;
                    this.RaisePropertyChanged("proveedor_rif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_documento_nombre {
            get {
                return this.tipo_documento_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_documento_nombreField, value) != true)) {
                    this.tipo_documento_nombreField = value;
                    this.RaisePropertyChanged("tipo_documento_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RepCompraService.IRepCompra")]
    public interface IRepCompra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCompra/GetResumenOperaciones", ReplyAction="http://tempuri.org/IRepCompra/GetResumenOperacionesResponse")]
        System.Collections.Generic.List<App.RepCompraService.RepCompra> GetResumenOperaciones(string idEmpresa, string id_moneda, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCompra/GetResumenOperaciones", ReplyAction="http://tempuri.org/IRepCompra/GetResumenOperacionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCompraService.RepCompra>> GetResumenOperacionesAsync(string idEmpresa, string id_moneda, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCompra/GetDetalleOperaciones", ReplyAction="http://tempuri.org/IRepCompra/GetDetalleOperacionesResponse")]
        System.Collections.Generic.List<App.RepCompraService.RepCompra> GetDetalleOperaciones(string idEmpresa, string id_moneda, string id_tipo, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCompra/GetDetalleOperaciones", ReplyAction="http://tempuri.org/IRepCompra/GetDetalleOperacionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCompraService.RepCompra>> GetDetalleOperacionesAsync(string idEmpresa, string id_moneda, string id_tipo, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCompra/GetProveedorOperaciones", ReplyAction="http://tempuri.org/IRepCompra/GetProveedorOperacionesResponse")]
        System.Collections.Generic.List<App.RepCompraService.RepCompra> GetProveedorOperaciones(string idEmpresa, string id_moneda, string id_proveedor, string desde, string hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepCompra/GetProveedorOperaciones", ReplyAction="http://tempuri.org/IRepCompra/GetProveedorOperacionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCompraService.RepCompra>> GetProveedorOperacionesAsync(string idEmpresa, string id_moneda, string id_proveedor, string desde, string hasta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepCompraChannel : App.RepCompraService.IRepCompra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepCompraClient : System.ServiceModel.ClientBase<App.RepCompraService.IRepCompra>, App.RepCompraService.IRepCompra {
        
        public RepCompraClient() {
        }
        
        public RepCompraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepCompraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepCompraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepCompraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<App.RepCompraService.RepCompra> GetResumenOperaciones(string idEmpresa, string id_moneda, string desde, string hasta) {
            return base.Channel.GetResumenOperaciones(idEmpresa, id_moneda, desde, hasta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCompraService.RepCompra>> GetResumenOperacionesAsync(string idEmpresa, string id_moneda, string desde, string hasta) {
            return base.Channel.GetResumenOperacionesAsync(idEmpresa, id_moneda, desde, hasta);
        }
        
        public System.Collections.Generic.List<App.RepCompraService.RepCompra> GetDetalleOperaciones(string idEmpresa, string id_moneda, string id_tipo, string desde, string hasta) {
            return base.Channel.GetDetalleOperaciones(idEmpresa, id_moneda, id_tipo, desde, hasta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCompraService.RepCompra>> GetDetalleOperacionesAsync(string idEmpresa, string id_moneda, string id_tipo, string desde, string hasta) {
            return base.Channel.GetDetalleOperacionesAsync(idEmpresa, id_moneda, id_tipo, desde, hasta);
        }
        
        public System.Collections.Generic.List<App.RepCompraService.RepCompra> GetProveedorOperaciones(string idEmpresa, string id_moneda, string id_proveedor, string desde, string hasta) {
            return base.Channel.GetProveedorOperaciones(idEmpresa, id_moneda, id_proveedor, desde, hasta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.RepCompraService.RepCompra>> GetProveedorOperacionesAsync(string idEmpresa, string id_moneda, string id_proveedor, string desde, string hasta) {
            return base.Channel.GetProveedorOperacionesAsync(idEmpresa, id_moneda, id_proveedor, desde, hasta);
        }
    }
}
