//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.VntClienteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VntCliente", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class VntCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double abonosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double abonos_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double deudaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double deuda_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double limite_creditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double total_monedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double abonos {
            get {
                return this.abonosField;
            }
            set {
                if ((this.abonosField.Equals(value) != true)) {
                    this.abonosField = value;
                    this.RaisePropertyChanged("abonos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double abonos_moneda {
            get {
                return this.abonos_monedaField;
            }
            set {
                if ((this.abonos_monedaField.Equals(value) != true)) {
                    this.abonos_monedaField = value;
                    this.RaisePropertyChanged("abonos_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double deuda {
            get {
                return this.deudaField;
            }
            set {
                if ((this.deudaField.Equals(value) != true)) {
                    this.deudaField = value;
                    this.RaisePropertyChanged("deuda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double deuda_moneda {
            get {
                return this.deuda_monedaField;
            }
            set {
                if ((this.deuda_monedaField.Equals(value) != true)) {
                    this.deuda_monedaField = value;
                    this.RaisePropertyChanged("deuda_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_empresa {
            get {
                return this.id_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_empresaField, value) != true)) {
                    this.id_empresaField = value;
                    this.RaisePropertyChanged("id_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double limite_credito {
            get {
                return this.limite_creditoField;
            }
            set {
                if ((this.limite_creditoField.Equals(value) != true)) {
                    this.limite_creditoField = value;
                    this.RaisePropertyChanged("limite_credito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionField, value) != true)) {
                    this.observacionField = value;
                    this.RaisePropertyChanged("observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rif {
            get {
                return this.rifField;
            }
            set {
                if ((object.ReferenceEquals(this.rifField, value) != true)) {
                    this.rifField = value;
                    this.RaisePropertyChanged("rif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double total_moneda {
            get {
                return this.total_monedaField;
            }
            set {
                if ((this.total_monedaField.Equals(value) != true)) {
                    this.total_monedaField = value;
                    this.RaisePropertyChanged("total_moneda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VntClienteService.IVntCliente")]
    public interface IVntCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVntCliente/GetList", ReplyAction="http://tempuri.org/IVntCliente/GetListResponse")]
        System.Collections.Generic.List<App.VntClienteService.VntCliente> GetList(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVntCliente/GetList", ReplyAction="http://tempuri.org/IVntCliente/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.VntClienteService.VntCliente>> GetListAsync(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVntCliente/GetOne", ReplyAction="http://tempuri.org/IVntCliente/GetOneResponse")]
        App.VntClienteService.VntCliente GetOne(string idEmpresa, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVntCliente/GetOne", ReplyAction="http://tempuri.org/IVntCliente/GetOneResponse")]
        System.Threading.Tasks.Task<App.VntClienteService.VntCliente> GetOneAsync(string idEmpresa, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVntCliente/SetOne", ReplyAction="http://tempuri.org/IVntCliente/SetOneResponse")]
        string SetOne(App.VntClienteService.VntCliente one);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVntCliente/SetOne", ReplyAction="http://tempuri.org/IVntCliente/SetOneResponse")]
        System.Threading.Tasks.Task<string> SetOneAsync(App.VntClienteService.VntCliente one);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVntClienteChannel : App.VntClienteService.IVntCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VntClienteClient : System.ServiceModel.ClientBase<App.VntClienteService.IVntCliente>, App.VntClienteService.IVntCliente {
        
        public VntClienteClient() {
        }
        
        public VntClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VntClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VntClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VntClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<App.VntClienteService.VntCliente> GetList(string idEmpresa) {
            return base.Channel.GetList(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.VntClienteService.VntCliente>> GetListAsync(string idEmpresa) {
            return base.Channel.GetListAsync(idEmpresa);
        }
        
        public App.VntClienteService.VntCliente GetOne(string idEmpresa, string id) {
            return base.Channel.GetOne(idEmpresa, id);
        }
        
        public System.Threading.Tasks.Task<App.VntClienteService.VntCliente> GetOneAsync(string idEmpresa, string id) {
            return base.Channel.GetOneAsync(idEmpresa, id);
        }
        
        public string SetOne(App.VntClienteService.VntCliente one) {
            return base.Channel.SetOne(one);
        }
        
        public System.Threading.Tasks.Task<string> SetOneAsync(App.VntClienteService.VntCliente one) {
            return base.Channel.SetOneAsync(one);
        }
    }
}
