//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.CmpOperacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CmpOperacion", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class CmpOperacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double base_imponible_taField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double base_imponible_ta_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double base_imponible_tgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double base_imponible_tg_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double base_imponible_trField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double base_imponible_tr_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_cotizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_destinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_doc_origenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_proveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_tipo_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_tipo_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_exentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_exento_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_iva_taField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_iva_ta_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_iva_tgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_iva_tg_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_iva_trField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_iva_tr_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_controlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_control_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_factura_afectadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_adicionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_alicuota_taField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_alicuota_tgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_alicuota_trField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_descuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proveedor_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proveedor_rifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_documento_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double total_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuario_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double base_imponible_ta {
            get {
                return this.base_imponible_taField;
            }
            set {
                if ((this.base_imponible_taField.Equals(value) != true)) {
                    this.base_imponible_taField = value;
                    this.RaisePropertyChanged("base_imponible_ta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double base_imponible_ta_moneda {
            get {
                return this.base_imponible_ta_monedaField;
            }
            set {
                if ((this.base_imponible_ta_monedaField.Equals(value) != true)) {
                    this.base_imponible_ta_monedaField = value;
                    this.RaisePropertyChanged("base_imponible_ta_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double base_imponible_tg {
            get {
                return this.base_imponible_tgField;
            }
            set {
                if ((this.base_imponible_tgField.Equals(value) != true)) {
                    this.base_imponible_tgField = value;
                    this.RaisePropertyChanged("base_imponible_tg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double base_imponible_tg_moneda {
            get {
                return this.base_imponible_tg_monedaField;
            }
            set {
                if ((this.base_imponible_tg_monedaField.Equals(value) != true)) {
                    this.base_imponible_tg_monedaField = value;
                    this.RaisePropertyChanged("base_imponible_tg_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double base_imponible_tr {
            get {
                return this.base_imponible_trField;
            }
            set {
                if ((this.base_imponible_trField.Equals(value) != true)) {
                    this.base_imponible_trField = value;
                    this.RaisePropertyChanged("base_imponible_tr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double base_imponible_tr_moneda {
            get {
                return this.base_imponible_tr_monedaField;
            }
            set {
                if ((this.base_imponible_tr_monedaField.Equals(value) != true)) {
                    this.base_imponible_tr_monedaField = value;
                    this.RaisePropertyChanged("base_imponible_tr_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_documento {
            get {
                return this.fecha_documentoField;
            }
            set {
                if ((this.fecha_documentoField.Equals(value) != true)) {
                    this.fecha_documentoField = value;
                    this.RaisePropertyChanged("fecha_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                if ((this.fecha_registroField.Equals(value) != true)) {
                    this.fecha_registroField = value;
                    this.RaisePropertyChanged("fecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_cotizacion {
            get {
                return this.id_cotizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_cotizacionField, value) != true)) {
                    this.id_cotizacionField = value;
                    this.RaisePropertyChanged("id_cotizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_destino {
            get {
                return this.id_destinoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_destinoField, value) != true)) {
                    this.id_destinoField = value;
                    this.RaisePropertyChanged("id_destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_doc_origen {
            get {
                return this.id_doc_origenField;
            }
            set {
                if ((object.ReferenceEquals(this.id_doc_origenField, value) != true)) {
                    this.id_doc_origenField = value;
                    this.RaisePropertyChanged("id_doc_origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_empresa {
            get {
                return this.id_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_empresaField, value) != true)) {
                    this.id_empresaField = value;
                    this.RaisePropertyChanged("id_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_estado {
            get {
                return this.id_estadoField;
            }
            set {
                if ((this.id_estadoField.Equals(value) != true)) {
                    this.id_estadoField = value;
                    this.RaisePropertyChanged("id_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_proveedor {
            get {
                return this.id_proveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.id_proveedorField, value) != true)) {
                    this.id_proveedorField = value;
                    this.RaisePropertyChanged("id_proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_status {
            get {
                return this.id_statusField;
            }
            set {
                if ((this.id_statusField.Equals(value) != true)) {
                    this.id_statusField = value;
                    this.RaisePropertyChanged("id_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_tipo_documento {
            get {
                return this.id_tipo_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_tipo_documentoField, value) != true)) {
                    this.id_tipo_documentoField = value;
                    this.RaisePropertyChanged("id_tipo_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_tipo_operacion {
            get {
                return this.id_tipo_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_tipo_operacionField, value) != true)) {
                    this.id_tipo_operacionField = value;
                    this.RaisePropertyChanged("id_tipo_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.id_usuarioField, value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_exento {
            get {
                return this.monto_exentoField;
            }
            set {
                if ((this.monto_exentoField.Equals(value) != true)) {
                    this.monto_exentoField = value;
                    this.RaisePropertyChanged("monto_exento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_exento_moneda {
            get {
                return this.monto_exento_monedaField;
            }
            set {
                if ((this.monto_exento_monedaField.Equals(value) != true)) {
                    this.monto_exento_monedaField = value;
                    this.RaisePropertyChanged("monto_exento_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_iva_ta {
            get {
                return this.monto_iva_taField;
            }
            set {
                if ((this.monto_iva_taField.Equals(value) != true)) {
                    this.monto_iva_taField = value;
                    this.RaisePropertyChanged("monto_iva_ta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_iva_ta_moneda {
            get {
                return this.monto_iva_ta_monedaField;
            }
            set {
                if ((this.monto_iva_ta_monedaField.Equals(value) != true)) {
                    this.monto_iva_ta_monedaField = value;
                    this.RaisePropertyChanged("monto_iva_ta_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_iva_tg {
            get {
                return this.monto_iva_tgField;
            }
            set {
                if ((this.monto_iva_tgField.Equals(value) != true)) {
                    this.monto_iva_tgField = value;
                    this.RaisePropertyChanged("monto_iva_tg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_iva_tg_moneda {
            get {
                return this.monto_iva_tg_monedaField;
            }
            set {
                if ((this.monto_iva_tg_monedaField.Equals(value) != true)) {
                    this.monto_iva_tg_monedaField = value;
                    this.RaisePropertyChanged("monto_iva_tg_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_iva_tr {
            get {
                return this.monto_iva_trField;
            }
            set {
                if ((this.monto_iva_trField.Equals(value) != true)) {
                    this.monto_iva_trField = value;
                    this.RaisePropertyChanged("monto_iva_tr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_iva_tr_moneda {
            get {
                return this.monto_iva_tr_monedaField;
            }
            set {
                if ((this.monto_iva_tr_monedaField.Equals(value) != true)) {
                    this.monto_iva_tr_monedaField = value;
                    this.RaisePropertyChanged("monto_iva_tr_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_control {
            get {
                return this.nro_controlField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_controlField, value) != true)) {
                    this.nro_controlField = value;
                    this.RaisePropertyChanged("nro_control");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_control_documento {
            get {
                return this.nro_control_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_control_documentoField, value) != true)) {
                    this.nro_control_documentoField = value;
                    this.RaisePropertyChanged("nro_control_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_documento {
            get {
                return this.nro_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_documentoField, value) != true)) {
                    this.nro_documentoField = value;
                    this.RaisePropertyChanged("nro_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_factura_afectada {
            get {
                return this.nro_factura_afectadaField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_factura_afectadaField, value) != true)) {
                    this.nro_factura_afectadaField = value;
                    this.RaisePropertyChanged("nro_factura_afectada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionField, value) != true)) {
                    this.observacionField = value;
                    this.RaisePropertyChanged("observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_adicional {
            get {
                return this.pct_adicionalField;
            }
            set {
                if ((this.pct_adicionalField.Equals(value) != true)) {
                    this.pct_adicionalField = value;
                    this.RaisePropertyChanged("pct_adicional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_alicuota_ta {
            get {
                return this.pct_alicuota_taField;
            }
            set {
                if ((this.pct_alicuota_taField.Equals(value) != true)) {
                    this.pct_alicuota_taField = value;
                    this.RaisePropertyChanged("pct_alicuota_ta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_alicuota_tg {
            get {
                return this.pct_alicuota_tgField;
            }
            set {
                if ((this.pct_alicuota_tgField.Equals(value) != true)) {
                    this.pct_alicuota_tgField = value;
                    this.RaisePropertyChanged("pct_alicuota_tg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_alicuota_tr {
            get {
                return this.pct_alicuota_trField;
            }
            set {
                if ((this.pct_alicuota_trField.Equals(value) != true)) {
                    this.pct_alicuota_trField = value;
                    this.RaisePropertyChanged("pct_alicuota_tr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_descuento {
            get {
                return this.pct_descuentoField;
            }
            set {
                if ((this.pct_descuentoField.Equals(value) != true)) {
                    this.pct_descuentoField = value;
                    this.RaisePropertyChanged("pct_descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string proveedor_nombre {
            get {
                return this.proveedor_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.proveedor_nombreField, value) != true)) {
                    this.proveedor_nombreField = value;
                    this.RaisePropertyChanged("proveedor_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string proveedor_rif {
            get {
                return this.proveedor_rifField;
            }
            set {
                if ((object.ReferenceEquals(this.proveedor_rifField, value) != true)) {
                    this.proveedor_rifField = value;
                    this.RaisePropertyChanged("proveedor_rif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_documento_nombre {
            get {
                return this.tipo_documento_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_documento_nombreField, value) != true)) {
                    this.tipo_documento_nombreField = value;
                    this.RaisePropertyChanged("tipo_documento_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double total_moneda {
            get {
                return this.total_monedaField;
            }
            set {
                if ((this.total_monedaField.Equals(value) != true)) {
                    this.total_monedaField = value;
                    this.RaisePropertyChanged("total_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_nombre {
            get {
                return this.usuario_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.usuario_nombreField, value) != true)) {
                    this.usuario_nombreField = value;
                    this.RaisePropertyChanged("usuario_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvMovimiento", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class InvMovimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costo_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_impuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_tipo_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_impuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_impuesto_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precio_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_unidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valor_impuestoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo_moneda {
            get {
                return this.costo_monedaField;
            }
            set {
                if ((this.costo_monedaField.Equals(value) != true)) {
                    this.costo_monedaField = value;
                    this.RaisePropertyChanged("costo_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_empresa {
            get {
                return this.id_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_empresaField, value) != true)) {
                    this.id_empresaField = value;
                    this.RaisePropertyChanged("id_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_impuesto {
            get {
                return this.id_impuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_impuestoField, value) != true)) {
                    this.id_impuestoField = value;
                    this.RaisePropertyChanged("id_impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_operacion {
            get {
                return this.id_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_operacionField, value) != true)) {
                    this.id_operacionField = value;
                    this.RaisePropertyChanged("id_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_productoField, value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_tipo_operacion {
            get {
                return this.id_tipo_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_tipo_operacionField, value) != true)) {
                    this.id_tipo_operacionField = value;
                    this.RaisePropertyChanged("id_tipo_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_impuesto {
            get {
                return this.monto_impuestoField;
            }
            set {
                if ((this.monto_impuestoField.Equals(value) != true)) {
                    this.monto_impuestoField = value;
                    this.RaisePropertyChanged("monto_impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_impuesto_moneda {
            get {
                return this.monto_impuesto_monedaField;
            }
            set {
                if ((this.monto_impuesto_monedaField.Equals(value) != true)) {
                    this.monto_impuesto_monedaField = value;
                    this.RaisePropertyChanged("monto_impuesto_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_moneda {
            get {
                return this.monto_monedaField;
            }
            set {
                if ((this.monto_monedaField.Equals(value) != true)) {
                    this.monto_monedaField = value;
                    this.RaisePropertyChanged("monto_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio_moneda {
            get {
                return this.precio_monedaField;
            }
            set {
                if ((this.precio_monedaField.Equals(value) != true)) {
                    this.precio_monedaField = value;
                    this.RaisePropertyChanged("precio_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_codigo {
            get {
                return this.producto_codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_codigoField, value) != true)) {
                    this.producto_codigoField = value;
                    this.RaisePropertyChanged("producto_codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_nombre {
            get {
                return this.producto_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_nombreField, value) != true)) {
                    this.producto_nombreField = value;
                    this.RaisePropertyChanged("producto_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_unidad {
            get {
                return this.producto_unidadField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_unidadField, value) != true)) {
                    this.producto_unidadField = value;
                    this.RaisePropertyChanged("producto_unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valor_impuesto {
            get {
                return this.valor_impuestoField;
            }
            set {
                if ((this.valor_impuestoField.Equals(value) != true)) {
                    this.valor_impuestoField = value;
                    this.RaisePropertyChanged("valor_impuesto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CmpOperacionService.ICmpOperacion")]
    public interface ICmpOperacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmpOperacion/GetList", ReplyAction="http://tempuri.org/ICmpOperacion/GetListResponse")]
        System.Collections.Generic.List<App.CmpOperacionService.CmpOperacion> GetList(string idEmpresa, string idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmpOperacion/GetList", ReplyAction="http://tempuri.org/ICmpOperacion/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.CmpOperacionService.CmpOperacion>> GetListAsync(string idEmpresa, string idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmpOperacion/GetOne", ReplyAction="http://tempuri.org/ICmpOperacion/GetOneResponse")]
        App.CmpOperacionService.CmpOperacion GetOne(string idEmpresa, string idTipo, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmpOperacion/GetOne", ReplyAction="http://tempuri.org/ICmpOperacion/GetOneResponse")]
        System.Threading.Tasks.Task<App.CmpOperacionService.CmpOperacion> GetOneAsync(string idEmpresa, string idTipo, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmpOperacion/SetOne", ReplyAction="http://tempuri.org/ICmpOperacion/SetOneResponse")]
        string SetOne(App.CmpOperacionService.CmpOperacion one, System.Collections.Generic.List<App.CmpOperacionService.InvMovimiento> detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmpOperacion/SetOne", ReplyAction="http://tempuri.org/ICmpOperacion/SetOneResponse")]
        System.Threading.Tasks.Task<string> SetOneAsync(App.CmpOperacionService.CmpOperacion one, System.Collections.Generic.List<App.CmpOperacionService.InvMovimiento> detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmpOperacion/NullOne", ReplyAction="http://tempuri.org/ICmpOperacion/NullOneResponse")]
        string NullOne(App.CmpOperacionService.CmpOperacion one, System.Collections.Generic.List<App.CmpOperacionService.InvMovimiento> detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmpOperacion/NullOne", ReplyAction="http://tempuri.org/ICmpOperacion/NullOneResponse")]
        System.Threading.Tasks.Task<string> NullOneAsync(App.CmpOperacionService.CmpOperacion one, System.Collections.Generic.List<App.CmpOperacionService.InvMovimiento> detail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICmpOperacionChannel : App.CmpOperacionService.ICmpOperacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CmpOperacionClient : System.ServiceModel.ClientBase<App.CmpOperacionService.ICmpOperacion>, App.CmpOperacionService.ICmpOperacion {
        
        public CmpOperacionClient() {
        }
        
        public CmpOperacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CmpOperacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CmpOperacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CmpOperacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<App.CmpOperacionService.CmpOperacion> GetList(string idEmpresa, string idTipo) {
            return base.Channel.GetList(idEmpresa, idTipo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.CmpOperacionService.CmpOperacion>> GetListAsync(string idEmpresa, string idTipo) {
            return base.Channel.GetListAsync(idEmpresa, idTipo);
        }
        
        public App.CmpOperacionService.CmpOperacion GetOne(string idEmpresa, string idTipo, string id) {
            return base.Channel.GetOne(idEmpresa, idTipo, id);
        }
        
        public System.Threading.Tasks.Task<App.CmpOperacionService.CmpOperacion> GetOneAsync(string idEmpresa, string idTipo, string id) {
            return base.Channel.GetOneAsync(idEmpresa, idTipo, id);
        }
        
        public string SetOne(App.CmpOperacionService.CmpOperacion one, System.Collections.Generic.List<App.CmpOperacionService.InvMovimiento> detail) {
            return base.Channel.SetOne(one, detail);
        }
        
        public System.Threading.Tasks.Task<string> SetOneAsync(App.CmpOperacionService.CmpOperacion one, System.Collections.Generic.List<App.CmpOperacionService.InvMovimiento> detail) {
            return base.Channel.SetOneAsync(one, detail);
        }
        
        public string NullOne(App.CmpOperacionService.CmpOperacion one, System.Collections.Generic.List<App.CmpOperacionService.InvMovimiento> detail) {
            return base.Channel.NullOne(one, detail);
        }
        
        public System.Threading.Tasks.Task<string> NullOneAsync(App.CmpOperacionService.CmpOperacion one, System.Collections.Generic.List<App.CmpOperacionService.InvMovimiento> detail) {
            return base.Channel.NullOneAsync(one, detail);
        }
    }
}
