//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.InvMovimientoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvMovimiento", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class InvMovimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costo_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_impuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_tipo_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_impuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_impuesto_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_comisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precio_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_unidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valor_impuestoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo_moneda {
            get {
                return this.costo_monedaField;
            }
            set {
                if ((this.costo_monedaField.Equals(value) != true)) {
                    this.costo_monedaField = value;
                    this.RaisePropertyChanged("costo_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_empresa {
            get {
                return this.id_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_empresaField, value) != true)) {
                    this.id_empresaField = value;
                    this.RaisePropertyChanged("id_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_impuesto {
            get {
                return this.id_impuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_impuestoField, value) != true)) {
                    this.id_impuestoField = value;
                    this.RaisePropertyChanged("id_impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_operacion {
            get {
                return this.id_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_operacionField, value) != true)) {
                    this.id_operacionField = value;
                    this.RaisePropertyChanged("id_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_productoField, value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_tipo_operacion {
            get {
                return this.id_tipo_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_tipo_operacionField, value) != true)) {
                    this.id_tipo_operacionField = value;
                    this.RaisePropertyChanged("id_tipo_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_impuesto {
            get {
                return this.monto_impuestoField;
            }
            set {
                if ((this.monto_impuestoField.Equals(value) != true)) {
                    this.monto_impuestoField = value;
                    this.RaisePropertyChanged("monto_impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_impuesto_moneda {
            get {
                return this.monto_impuesto_monedaField;
            }
            set {
                if ((this.monto_impuesto_monedaField.Equals(value) != true)) {
                    this.monto_impuesto_monedaField = value;
                    this.RaisePropertyChanged("monto_impuesto_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_moneda {
            get {
                return this.monto_monedaField;
            }
            set {
                if ((this.monto_monedaField.Equals(value) != true)) {
                    this.monto_monedaField = value;
                    this.RaisePropertyChanged("monto_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_comision {
            get {
                return this.pct_comisionField;
            }
            set {
                if ((this.pct_comisionField.Equals(value) != true)) {
                    this.pct_comisionField = value;
                    this.RaisePropertyChanged("pct_comision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio_moneda {
            get {
                return this.precio_monedaField;
            }
            set {
                if ((this.precio_monedaField.Equals(value) != true)) {
                    this.precio_monedaField = value;
                    this.RaisePropertyChanged("precio_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_codigo {
            get {
                return this.producto_codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_codigoField, value) != true)) {
                    this.producto_codigoField = value;
                    this.RaisePropertyChanged("producto_codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_nombre {
            get {
                return this.producto_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_nombreField, value) != true)) {
                    this.producto_nombreField = value;
                    this.RaisePropertyChanged("producto_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_unidad {
            get {
                return this.producto_unidadField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_unidadField, value) != true)) {
                    this.producto_unidadField = value;
                    this.RaisePropertyChanged("producto_unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valor_impuesto {
            get {
                return this.valor_impuestoField;
            }
            set {
                if ((this.valor_impuestoField.Equals(value) != true)) {
                    this.valor_impuestoField = value;
                    this.RaisePropertyChanged("valor_impuesto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvMovimientoService.IInvMovimiento")]
    public interface IInvMovimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvMovimiento/Delete", ReplyAction="http://tempuri.org/IInvMovimiento/DeleteResponse")]
        bool Delete(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvMovimiento/Delete", ReplyAction="http://tempuri.org/IInvMovimiento/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvMovimiento/GetList", ReplyAction="http://tempuri.org/IInvMovimiento/GetListResponse")]
        System.Collections.Generic.List<App.InvMovimientoService.InvMovimiento> GetList(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvMovimiento/GetList", ReplyAction="http://tempuri.org/IInvMovimiento/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvMovimientoService.InvMovimiento>> GetListAsync(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvMovimiento/GetListByOrigen", ReplyAction="http://tempuri.org/IInvMovimiento/GetListByOrigenResponse")]
        System.Collections.Generic.List<App.InvMovimientoService.InvMovimiento> GetListByOrigen(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvMovimiento/GetListByOrigen", ReplyAction="http://tempuri.org/IInvMovimiento/GetListByOrigenResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvMovimientoService.InvMovimiento>> GetListByOrigenAsync(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvMovimiento/SetOne", ReplyAction="http://tempuri.org/IInvMovimiento/SetOneResponse")]
        string SetOne(App.InvMovimientoService.InvMovimiento one);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvMovimiento/SetOne", ReplyAction="http://tempuri.org/IInvMovimiento/SetOneResponse")]
        System.Threading.Tasks.Task<string> SetOneAsync(App.InvMovimientoService.InvMovimiento one);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvMovimientoChannel : App.InvMovimientoService.IInvMovimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvMovimientoClient : System.ServiceModel.ClientBase<App.InvMovimientoService.IInvMovimiento>, App.InvMovimientoService.IInvMovimiento {
        
        public InvMovimientoClient() {
        }
        
        public InvMovimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvMovimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvMovimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvMovimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Delete(string idOperacion) {
            return base.Channel.Delete(idOperacion);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string idOperacion) {
            return base.Channel.DeleteAsync(idOperacion);
        }
        
        public System.Collections.Generic.List<App.InvMovimientoService.InvMovimiento> GetList(string idOperacion) {
            return base.Channel.GetList(idOperacion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvMovimientoService.InvMovimiento>> GetListAsync(string idOperacion) {
            return base.Channel.GetListAsync(idOperacion);
        }
        
        public System.Collections.Generic.List<App.InvMovimientoService.InvMovimiento> GetListByOrigen(string idOperacion) {
            return base.Channel.GetListByOrigen(idOperacion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvMovimientoService.InvMovimiento>> GetListByOrigenAsync(string idOperacion) {
            return base.Channel.GetListByOrigenAsync(idOperacion);
        }
        
        public string SetOne(App.InvMovimientoService.InvMovimiento one) {
            return base.Channel.SetOne(one);
        }
        
        public System.Threading.Tasks.Task<string> SetOneAsync(App.InvMovimientoService.InvMovimiento one) {
            return base.Channel.SetOneAsync(one);
        }
    }
}
