//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.SisListasService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SisListas", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class SisListas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string campoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_padreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                if ((object.ReferenceEquals(this.campoField, value) != true)) {
                    this.campoField = value;
                    this.RaisePropertyChanged("campo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descrip {
            get {
                return this.descripField;
            }
            set {
                if ((object.ReferenceEquals(this.descripField, value) != true)) {
                    this.descripField = value;
                    this.RaisePropertyChanged("descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_padre {
            get {
                return this.id_padreField;
            }
            set {
                if ((object.ReferenceEquals(this.id_padreField, value) != true)) {
                    this.id_padreField = value;
                    this.RaisePropertyChanged("id_padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SisListasService.ISisListas")]
    public interface ISisListas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisListas/GetList", ReplyAction="http://tempuri.org/ISisListas/GetListResponse")]
        System.Collections.Generic.List<App.SisListasService.SisListas> GetList(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisListas/GetList", ReplyAction="http://tempuri.org/ISisListas/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.SisListasService.SisListas>> GetListAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisListas/GetListByCampo", ReplyAction="http://tempuri.org/ISisListas/GetListByCampoResponse")]
        System.Collections.Generic.List<App.SisListasService.SisListas> GetListByCampo(string campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisListas/GetListByCampo", ReplyAction="http://tempuri.org/ISisListas/GetListByCampoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.SisListasService.SisListas>> GetListByCampoAsync(string campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisListas/GetOne", ReplyAction="http://tempuri.org/ISisListas/GetOneResponse")]
        App.SisListasService.SisListas GetOne(string idEmpresa, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisListas/GetOne", ReplyAction="http://tempuri.org/ISisListas/GetOneResponse")]
        System.Threading.Tasks.Task<App.SisListasService.SisListas> GetOneAsync(string idEmpresa, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisListas/SetOne", ReplyAction="http://tempuri.org/ISisListas/SetOneResponse")]
        string SetOne(App.SisListasService.SisListas one);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisListas/SetOne", ReplyAction="http://tempuri.org/ISisListas/SetOneResponse")]
        System.Threading.Tasks.Task<string> SetOneAsync(App.SisListasService.SisListas one);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISisListasChannel : App.SisListasService.ISisListas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SisListasClient : System.ServiceModel.ClientBase<App.SisListasService.ISisListas>, App.SisListasService.ISisListas {
        
        public SisListasClient() {
        }
        
        public SisListasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SisListasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SisListasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SisListasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<App.SisListasService.SisListas> GetList(string id) {
            return base.Channel.GetList(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.SisListasService.SisListas>> GetListAsync(string id) {
            return base.Channel.GetListAsync(id);
        }
        
        public System.Collections.Generic.List<App.SisListasService.SisListas> GetListByCampo(string campo) {
            return base.Channel.GetListByCampo(campo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.SisListasService.SisListas>> GetListByCampoAsync(string campo) {
            return base.Channel.GetListByCampoAsync(campo);
        }
        
        public App.SisListasService.SisListas GetOne(string idEmpresa, string id) {
            return base.Channel.GetOne(idEmpresa, id);
        }
        
        public System.Threading.Tasks.Task<App.SisListasService.SisListas> GetOneAsync(string idEmpresa, string id) {
            return base.Channel.GetOneAsync(idEmpresa, id);
        }
        
        public string SetOne(App.SisListasService.SisListas one) {
            return base.Channel.SetOne(one);
        }
        
        public System.Threading.Tasks.Task<string> SetOneAsync(App.SisListasService.SisListas one) {
            return base.Channel.SetOneAsync(one);
        }
    }
}
