//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.SisEmpresaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SisEmpresa", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class SisEmpresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool es_inactivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool es_modo_fiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_contratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instrumentos_pagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moneda_defectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string monedasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_fiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool es_inactivo {
            get {
                return this.es_inactivoField;
            }
            set {
                if ((this.es_inactivoField.Equals(value) != true)) {
                    this.es_inactivoField = value;
                    this.RaisePropertyChanged("es_inactivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool es_modo_fiscal {
            get {
                return this.es_modo_fiscalField;
            }
            set {
                if ((this.es_modo_fiscalField.Equals(value) != true)) {
                    this.es_modo_fiscalField = value;
                    this.RaisePropertyChanged("es_modo_fiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_contrato {
            get {
                return this.fecha_contratoField;
            }
            set {
                if ((this.fecha_contratoField.Equals(value) != true)) {
                    this.fecha_contratoField = value;
                    this.RaisePropertyChanged("fecha_contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instrumentos_pago {
            get {
                return this.instrumentos_pagoField;
            }
            set {
                if ((object.ReferenceEquals(this.instrumentos_pagoField, value) != true)) {
                    this.instrumentos_pagoField = value;
                    this.RaisePropertyChanged("instrumentos_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moneda_defecto {
            get {
                return this.moneda_defectoField;
            }
            set {
                if ((object.ReferenceEquals(this.moneda_defectoField, value) != true)) {
                    this.moneda_defectoField = value;
                    this.RaisePropertyChanged("moneda_defecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string monedas {
            get {
                return this.monedasField;
            }
            set {
                if ((object.ReferenceEquals(this.monedasField, value) != true)) {
                    this.monedasField = value;
                    this.RaisePropertyChanged("monedas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_fiscal {
            get {
                return this.pct_fiscalField;
            }
            set {
                if ((this.pct_fiscalField.Equals(value) != true)) {
                    this.pct_fiscalField = value;
                    this.RaisePropertyChanged("pct_fiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rif {
            get {
                return this.rifField;
            }
            set {
                if ((object.ReferenceEquals(this.rifField, value) != true)) {
                    this.rifField = value;
                    this.RaisePropertyChanged("rif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SisEmpresaService.ISisEmpresa")]
    public interface ISisEmpresa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisEmpresa/GetOne", ReplyAction="http://tempuri.org/ISisEmpresa/GetOneResponse")]
        App.SisEmpresaService.SisEmpresa GetOne(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisEmpresa/GetOne", ReplyAction="http://tempuri.org/ISisEmpresa/GetOneResponse")]
        System.Threading.Tasks.Task<App.SisEmpresaService.SisEmpresa> GetOneAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisEmpresa/SetOne", ReplyAction="http://tempuri.org/ISisEmpresa/SetOneResponse")]
        string SetOne(App.SisEmpresaService.SisEmpresa one);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISisEmpresa/SetOne", ReplyAction="http://tempuri.org/ISisEmpresa/SetOneResponse")]
        System.Threading.Tasks.Task<string> SetOneAsync(App.SisEmpresaService.SisEmpresa one);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISisEmpresaChannel : App.SisEmpresaService.ISisEmpresa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SisEmpresaClient : System.ServiceModel.ClientBase<App.SisEmpresaService.ISisEmpresa>, App.SisEmpresaService.ISisEmpresa {
        
        public SisEmpresaClient() {
        }
        
        public SisEmpresaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SisEmpresaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SisEmpresaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SisEmpresaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public App.SisEmpresaService.SisEmpresa GetOne(string id) {
            return base.Channel.GetOne(id);
        }
        
        public System.Threading.Tasks.Task<App.SisEmpresaService.SisEmpresa> GetOneAsync(string id) {
            return base.Channel.GetOneAsync(id);
        }
        
        public string SetOne(App.SisEmpresaService.SisEmpresa one) {
            return base.Channel.SetOne(one);
        }
        
        public System.Threading.Tasks.Task<string> SetOneAsync(App.SisEmpresaService.SisEmpresa one) {
            return base.Channel.SetOneAsync(one);
        }
    }
}
