//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.CajMovimientoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CajMovimiento", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class CajMovimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string banco_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuenta_bancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuenta_numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double factorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_bancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_instrumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_tipo_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instrumento_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moneda_descripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moneda_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numero_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string banco_nombre {
            get {
                return this.banco_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.banco_nombreField, value) != true)) {
                    this.banco_nombreField = value;
                    this.RaisePropertyChanged("banco_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuenta_banco {
            get {
                return this.cuenta_bancoField;
            }
            set {
                if ((object.ReferenceEquals(this.cuenta_bancoField, value) != true)) {
                    this.cuenta_bancoField = value;
                    this.RaisePropertyChanged("cuenta_banco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuenta_numero {
            get {
                return this.cuenta_numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.cuenta_numeroField, value) != true)) {
                    this.cuenta_numeroField = value;
                    this.RaisePropertyChanged("cuenta_numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double factor {
            get {
                return this.factorField;
            }
            set {
                if ((this.factorField.Equals(value) != true)) {
                    this.factorField = value;
                    this.RaisePropertyChanged("factor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_banco {
            get {
                return this.id_bancoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_bancoField, value) != true)) {
                    this.id_bancoField = value;
                    this.RaisePropertyChanged("id_banco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_cuenta {
            get {
                return this.id_cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_cuentaField, value) != true)) {
                    this.id_cuentaField = value;
                    this.RaisePropertyChanged("id_cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_empresa {
            get {
                return this.id_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_empresaField, value) != true)) {
                    this.id_empresaField = value;
                    this.RaisePropertyChanged("id_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_instrumento {
            get {
                return this.id_instrumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_instrumentoField, value) != true)) {
                    this.id_instrumentoField = value;
                    this.RaisePropertyChanged("id_instrumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_moneda {
            get {
                return this.id_monedaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_monedaField, value) != true)) {
                    this.id_monedaField = value;
                    this.RaisePropertyChanged("id_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_operacion {
            get {
                return this.id_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_operacionField, value) != true)) {
                    this.id_operacionField = value;
                    this.RaisePropertyChanged("id_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_tipo_operacion {
            get {
                return this.id_tipo_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_tipo_operacionField, value) != true)) {
                    this.id_tipo_operacionField = value;
                    this.RaisePropertyChanged("id_tipo_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instrumento_nombre {
            get {
                return this.instrumento_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.instrumento_nombreField, value) != true)) {
                    this.instrumento_nombreField = value;
                    this.RaisePropertyChanged("instrumento_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moneda_descrip {
            get {
                return this.moneda_descripField;
            }
            set {
                if ((object.ReferenceEquals(this.moneda_descripField, value) != true)) {
                    this.moneda_descripField = value;
                    this.RaisePropertyChanged("moneda_descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moneda_nombre {
            get {
                return this.moneda_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.moneda_nombreField, value) != true)) {
                    this.moneda_nombreField = value;
                    this.RaisePropertyChanged("moneda_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_moneda {
            get {
                return this.monto_monedaField;
            }
            set {
                if ((this.monto_monedaField.Equals(value) != true)) {
                    this.monto_monedaField = value;
                    this.RaisePropertyChanged("monto_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero_operacion {
            get {
                return this.numero_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.numero_operacionField, value) != true)) {
                    this.numero_operacionField = value;
                    this.RaisePropertyChanged("numero_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CajMovimientoService.ICajMovimiento")]
    public interface ICajMovimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICajMovimiento/Delete", ReplyAction="http://tempuri.org/ICajMovimiento/DeleteResponse")]
        bool Delete(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICajMovimiento/Delete", ReplyAction="http://tempuri.org/ICajMovimiento/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICajMovimiento/GetList", ReplyAction="http://tempuri.org/ICajMovimiento/GetListResponse")]
        System.Collections.Generic.List<App.CajMovimientoService.CajMovimiento> GetList(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICajMovimiento/GetList", ReplyAction="http://tempuri.org/ICajMovimiento/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.CajMovimientoService.CajMovimiento>> GetListAsync(string idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICajMovimiento/SetOne", ReplyAction="http://tempuri.org/ICajMovimiento/SetOneResponse")]
        string SetOne(App.CajMovimientoService.CajMovimiento one);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICajMovimiento/SetOne", ReplyAction="http://tempuri.org/ICajMovimiento/SetOneResponse")]
        System.Threading.Tasks.Task<string> SetOneAsync(App.CajMovimientoService.CajMovimiento one);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICajMovimientoChannel : App.CajMovimientoService.ICajMovimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CajMovimientoClient : System.ServiceModel.ClientBase<App.CajMovimientoService.ICajMovimiento>, App.CajMovimientoService.ICajMovimiento {
        
        public CajMovimientoClient() {
        }
        
        public CajMovimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CajMovimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajMovimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajMovimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Delete(string idOperacion) {
            return base.Channel.Delete(idOperacion);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string idOperacion) {
            return base.Channel.DeleteAsync(idOperacion);
        }
        
        public System.Collections.Generic.List<App.CajMovimientoService.CajMovimiento> GetList(string idOperacion) {
            return base.Channel.GetList(idOperacion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.CajMovimientoService.CajMovimiento>> GetListAsync(string idOperacion) {
            return base.Channel.GetListAsync(idOperacion);
        }
        
        public string SetOne(App.CajMovimientoService.CajMovimiento one) {
            return base.Channel.SetOne(one);
        }
        
        public System.Threading.Tasks.Task<string> SetOneAsync(App.CajMovimientoService.CajMovimiento one) {
            return base.Channel.SetOneAsync(one);
        }
    }
}
