//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.InvOperacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvOperacion", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class InvOperacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_destinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_tipo_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_controlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuario_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                if ((this.fecha_registroField.Equals(value) != true)) {
                    this.fecha_registroField = value;
                    this.RaisePropertyChanged("fecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_destino {
            get {
                return this.id_destinoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_destinoField, value) != true)) {
                    this.id_destinoField = value;
                    this.RaisePropertyChanged("id_destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_empresa {
            get {
                return this.id_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_empresaField, value) != true)) {
                    this.id_empresaField = value;
                    this.RaisePropertyChanged("id_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_estado {
            get {
                return this.id_estadoField;
            }
            set {
                if ((this.id_estadoField.Equals(value) != true)) {
                    this.id_estadoField = value;
                    this.RaisePropertyChanged("id_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_status {
            get {
                return this.id_statusField;
            }
            set {
                if ((this.id_statusField.Equals(value) != true)) {
                    this.id_statusField = value;
                    this.RaisePropertyChanged("id_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_tipo_operacion {
            get {
                return this.id_tipo_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_tipo_operacionField, value) != true)) {
                    this.id_tipo_operacionField = value;
                    this.RaisePropertyChanged("id_tipo_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.id_usuarioField, value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_control {
            get {
                return this.nro_controlField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_controlField, value) != true)) {
                    this.nro_controlField = value;
                    this.RaisePropertyChanged("nro_control");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionField, value) != true)) {
                    this.observacionField = value;
                    this.RaisePropertyChanged("observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_nombre {
            get {
                return this.usuario_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.usuario_nombreField, value) != true)) {
                    this.usuario_nombreField = value;
                    this.RaisePropertyChanged("usuario_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvMovimiento", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class InvMovimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costo_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_impuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_tipo_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_impuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_impuesto_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double monto_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precio_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producto_unidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valor_impuestoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo_moneda {
            get {
                return this.costo_monedaField;
            }
            set {
                if ((this.costo_monedaField.Equals(value) != true)) {
                    this.costo_monedaField = value;
                    this.RaisePropertyChanged("costo_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_empresa {
            get {
                return this.id_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_empresaField, value) != true)) {
                    this.id_empresaField = value;
                    this.RaisePropertyChanged("id_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_impuesto {
            get {
                return this.id_impuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_impuestoField, value) != true)) {
                    this.id_impuestoField = value;
                    this.RaisePropertyChanged("id_impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_operacion {
            get {
                return this.id_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_operacionField, value) != true)) {
                    this.id_operacionField = value;
                    this.RaisePropertyChanged("id_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_productoField, value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_tipo_operacion {
            get {
                return this.id_tipo_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.id_tipo_operacionField, value) != true)) {
                    this.id_tipo_operacionField = value;
                    this.RaisePropertyChanged("id_tipo_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_impuesto {
            get {
                return this.monto_impuestoField;
            }
            set {
                if ((this.monto_impuestoField.Equals(value) != true)) {
                    this.monto_impuestoField = value;
                    this.RaisePropertyChanged("monto_impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_impuesto_moneda {
            get {
                return this.monto_impuesto_monedaField;
            }
            set {
                if ((this.monto_impuesto_monedaField.Equals(value) != true)) {
                    this.monto_impuesto_monedaField = value;
                    this.RaisePropertyChanged("monto_impuesto_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto_moneda {
            get {
                return this.monto_monedaField;
            }
            set {
                if ((this.monto_monedaField.Equals(value) != true)) {
                    this.monto_monedaField = value;
                    this.RaisePropertyChanged("monto_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio_moneda {
            get {
                return this.precio_monedaField;
            }
            set {
                if ((this.precio_monedaField.Equals(value) != true)) {
                    this.precio_monedaField = value;
                    this.RaisePropertyChanged("precio_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_codigo {
            get {
                return this.producto_codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_codigoField, value) != true)) {
                    this.producto_codigoField = value;
                    this.RaisePropertyChanged("producto_codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_nombre {
            get {
                return this.producto_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_nombreField, value) != true)) {
                    this.producto_nombreField = value;
                    this.RaisePropertyChanged("producto_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto_unidad {
            get {
                return this.producto_unidadField;
            }
            set {
                if ((object.ReferenceEquals(this.producto_unidadField, value) != true)) {
                    this.producto_unidadField = value;
                    this.RaisePropertyChanged("producto_unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valor_impuesto {
            get {
                return this.valor_impuestoField;
            }
            set {
                if ((this.valor_impuestoField.Equals(value) != true)) {
                    this.valor_impuestoField = value;
                    this.RaisePropertyChanged("valor_impuesto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvOperacionService.IInvOperacion")]
    public interface IInvOperacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvOperacion/GetList", ReplyAction="http://tempuri.org/IInvOperacion/GetListResponse")]
        System.Collections.Generic.List<App.InvOperacionService.InvOperacion> GetList(string idEmpresa, string idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvOperacion/GetList", ReplyAction="http://tempuri.org/IInvOperacion/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvOperacionService.InvOperacion>> GetListAsync(string idEmpresa, string idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvOperacion/GetOne", ReplyAction="http://tempuri.org/IInvOperacion/GetOneResponse")]
        App.InvOperacionService.InvOperacion GetOne(string idEmpresa, string idTipo, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvOperacion/GetOne", ReplyAction="http://tempuri.org/IInvOperacion/GetOneResponse")]
        System.Threading.Tasks.Task<App.InvOperacionService.InvOperacion> GetOneAsync(string idEmpresa, string idTipo, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvOperacion/SetOne", ReplyAction="http://tempuri.org/IInvOperacion/SetOneResponse")]
        string SetOne(App.InvOperacionService.InvOperacion one, System.Collections.Generic.List<App.InvOperacionService.InvMovimiento> detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvOperacion/SetOne", ReplyAction="http://tempuri.org/IInvOperacion/SetOneResponse")]
        System.Threading.Tasks.Task<string> SetOneAsync(App.InvOperacionService.InvOperacion one, System.Collections.Generic.List<App.InvOperacionService.InvMovimiento> detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvOperacion/NullOne", ReplyAction="http://tempuri.org/IInvOperacion/NullOneResponse")]
        string NullOne(App.InvOperacionService.InvOperacion one, System.Collections.Generic.List<App.InvOperacionService.InvMovimiento> detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvOperacion/NullOne", ReplyAction="http://tempuri.org/IInvOperacion/NullOneResponse")]
        System.Threading.Tasks.Task<string> NullOneAsync(App.InvOperacionService.InvOperacion one, System.Collections.Generic.List<App.InvOperacionService.InvMovimiento> detail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvOperacionChannel : App.InvOperacionService.IInvOperacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvOperacionClient : System.ServiceModel.ClientBase<App.InvOperacionService.IInvOperacion>, App.InvOperacionService.IInvOperacion {
        
        public InvOperacionClient() {
        }
        
        public InvOperacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvOperacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvOperacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvOperacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<App.InvOperacionService.InvOperacion> GetList(string idEmpresa, string idTipo) {
            return base.Channel.GetList(idEmpresa, idTipo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvOperacionService.InvOperacion>> GetListAsync(string idEmpresa, string idTipo) {
            return base.Channel.GetListAsync(idEmpresa, idTipo);
        }
        
        public App.InvOperacionService.InvOperacion GetOne(string idEmpresa, string idTipo, string id) {
            return base.Channel.GetOne(idEmpresa, idTipo, id);
        }
        
        public System.Threading.Tasks.Task<App.InvOperacionService.InvOperacion> GetOneAsync(string idEmpresa, string idTipo, string id) {
            return base.Channel.GetOneAsync(idEmpresa, idTipo, id);
        }
        
        public string SetOne(App.InvOperacionService.InvOperacion one, System.Collections.Generic.List<App.InvOperacionService.InvMovimiento> detail) {
            return base.Channel.SetOne(one, detail);
        }
        
        public System.Threading.Tasks.Task<string> SetOneAsync(App.InvOperacionService.InvOperacion one, System.Collections.Generic.List<App.InvOperacionService.InvMovimiento> detail) {
            return base.Channel.SetOneAsync(one, detail);
        }
        
        public string NullOne(App.InvOperacionService.InvOperacion one, System.Collections.Generic.List<App.InvOperacionService.InvMovimiento> detail) {
            return base.Channel.NullOne(one, detail);
        }
        
        public System.Threading.Tasks.Task<string> NullOneAsync(App.InvOperacionService.InvOperacion one, System.Collections.Generic.List<App.InvOperacionService.InvMovimiento> detail) {
            return base.Channel.NullOneAsync(one, detail);
        }
    }
}
