//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.InvProductoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvProducto", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class InvProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cantidad_empaqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoria_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costo_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcion_webField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool es_inactivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short es_visible_webField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double existenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_categoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_impuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_unidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double impuesto_valorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_webField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_comisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pct_utilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precio_monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidad_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cantidad_empaque {
            get {
                return this.cantidad_empaqueField;
            }
            set {
                if ((this.cantidad_empaqueField.Equals(value) != true)) {
                    this.cantidad_empaqueField = value;
                    this.RaisePropertyChanged("cantidad_empaque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoria_nombre {
            get {
                return this.categoria_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.categoria_nombreField, value) != true)) {
                    this.categoria_nombreField = value;
                    this.RaisePropertyChanged("categoria_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo_moneda {
            get {
                return this.costo_monedaField;
            }
            set {
                if ((this.costo_monedaField.Equals(value) != true)) {
                    this.costo_monedaField = value;
                    this.RaisePropertyChanged("costo_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion_web {
            get {
                return this.descripcion_webField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcion_webField, value) != true)) {
                    this.descripcion_webField = value;
                    this.RaisePropertyChanged("descripcion_web");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool es_inactivo {
            get {
                return this.es_inactivoField;
            }
            set {
                if ((this.es_inactivoField.Equals(value) != true)) {
                    this.es_inactivoField = value;
                    this.RaisePropertyChanged("es_inactivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short es_visible_web {
            get {
                return this.es_visible_webField;
            }
            set {
                if ((this.es_visible_webField.Equals(value) != true)) {
                    this.es_visible_webField = value;
                    this.RaisePropertyChanged("es_visible_web");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double existencia {
            get {
                return this.existenciaField;
            }
            set {
                if ((this.existenciaField.Equals(value) != true)) {
                    this.existenciaField = value;
                    this.RaisePropertyChanged("existencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_categoria {
            get {
                return this.id_categoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_categoriaField, value) != true)) {
                    this.id_categoriaField = value;
                    this.RaisePropertyChanged("id_categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_empresa {
            get {
                return this.id_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_empresaField, value) != true)) {
                    this.id_empresaField = value;
                    this.RaisePropertyChanged("id_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_impuesto {
            get {
                return this.id_impuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_impuestoField, value) != true)) {
                    this.id_impuestoField = value;
                    this.RaisePropertyChanged("id_impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_unidad {
            get {
                return this.id_unidadField;
            }
            set {
                if ((object.ReferenceEquals(this.id_unidadField, value) != true)) {
                    this.id_unidadField = value;
                    this.RaisePropertyChanged("id_unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double impuesto_valor {
            get {
                return this.impuesto_valorField;
            }
            set {
                if ((this.impuesto_valorField.Equals(value) != true)) {
                    this.impuesto_valorField = value;
                    this.RaisePropertyChanged("impuesto_valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre_web {
            get {
                return this.nombre_webField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_webField, value) != true)) {
                    this.nombre_webField = value;
                    this.RaisePropertyChanged("nombre_web");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_comision {
            get {
                return this.pct_comisionField;
            }
            set {
                if ((this.pct_comisionField.Equals(value) != true)) {
                    this.pct_comisionField = value;
                    this.RaisePropertyChanged("pct_comision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pct_utilidad {
            get {
                return this.pct_utilidadField;
            }
            set {
                if ((this.pct_utilidadField.Equals(value) != true)) {
                    this.pct_utilidadField = value;
                    this.RaisePropertyChanged("pct_utilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio_moneda {
            get {
                return this.precio_monedaField;
            }
            set {
                if ((this.precio_monedaField.Equals(value) != true)) {
                    this.precio_monedaField = value;
                    this.RaisePropertyChanged("precio_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unidad_nombre {
            get {
                return this.unidad_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.unidad_nombreField, value) != true)) {
                    this.unidad_nombreField = value;
                    this.RaisePropertyChanged("unidad_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvProductoService.IInvProducto")]
    public interface IInvProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvProducto/GetList", ReplyAction="http://tempuri.org/IInvProducto/GetListResponse")]
        System.Collections.Generic.List<App.InvProductoService.InvProducto> GetList(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvProducto/GetList", ReplyAction="http://tempuri.org/IInvProducto/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvProductoService.InvProducto>> GetListAsync(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvProducto/GetListPV", ReplyAction="http://tempuri.org/IInvProducto/GetListPVResponse")]
        System.Collections.Generic.List<App.InvProductoService.InvProducto> GetListPV(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvProducto/GetListPV", ReplyAction="http://tempuri.org/IInvProducto/GetListPVResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvProductoService.InvProducto>> GetListPVAsync(string idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvProducto/GetOne", ReplyAction="http://tempuri.org/IInvProducto/GetOneResponse")]
        App.InvProductoService.InvProducto GetOne(string idEmpresa, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvProducto/GetOne", ReplyAction="http://tempuri.org/IInvProducto/GetOneResponse")]
        System.Threading.Tasks.Task<App.InvProductoService.InvProducto> GetOneAsync(string idEmpresa, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvProducto/SetOne", ReplyAction="http://tempuri.org/IInvProducto/SetOneResponse")]
        string SetOne(App.InvProductoService.InvProducto one);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvProducto/SetOne", ReplyAction="http://tempuri.org/IInvProducto/SetOneResponse")]
        System.Threading.Tasks.Task<string> SetOneAsync(App.InvProductoService.InvProducto one);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvProductoChannel : App.InvProductoService.IInvProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvProductoClient : System.ServiceModel.ClientBase<App.InvProductoService.IInvProducto>, App.InvProductoService.IInvProducto {
        
        public InvProductoClient() {
        }
        
        public InvProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<App.InvProductoService.InvProducto> GetList(string idEmpresa) {
            return base.Channel.GetList(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvProductoService.InvProducto>> GetListAsync(string idEmpresa) {
            return base.Channel.GetListAsync(idEmpresa);
        }
        
        public System.Collections.Generic.List<App.InvProductoService.InvProducto> GetListPV(string idEmpresa) {
            return base.Channel.GetListPV(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.InvProductoService.InvProducto>> GetListPVAsync(string idEmpresa) {
            return base.Channel.GetListPVAsync(idEmpresa);
        }
        
        public App.InvProductoService.InvProducto GetOne(string idEmpresa, string id) {
            return base.Channel.GetOne(idEmpresa, id);
        }
        
        public System.Threading.Tasks.Task<App.InvProductoService.InvProducto> GetOneAsync(string idEmpresa, string id) {
            return base.Channel.GetOneAsync(idEmpresa, id);
        }
        
        public string SetOne(App.InvProductoService.InvProducto one) {
            return base.Channel.SetOne(one);
        }
        
        public System.Threading.Tasks.Task<string> SetOneAsync(App.InvProductoService.InvProducto one) {
            return base.Channel.SetOneAsync(one);
        }
    }
}
